apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingAdmissionPolicy
metadata:
  name: podgroup-mutation-policy
  labels:
    volcano.sh/component: podgroup-webhook
    volcano.sh/migration: map
spec:
  failurePolicy: Fail
  matchConstraints:
  - resourceRules:
    - operations: ["CREATE", "UPDATE"]
      apiGroups: ["scheduling.volcano.sh"]
      apiVersions: ["v1beta1"]
      resources: ["podgroups"]
  mutations:
  # 1. Default Queue Assignment - Set default queue when not specified
  # Note: This is a simplified version that doesn't include namespace-based assignment
  # due to CEL limitations in accessing namespace annotations
  - target:
      group: scheduling.volcano.sh
      version: v1beta1
      kind: PodGroup
    patchType: strategic
    patches:
    - op: add
      path: /spec/queue
      value: "default"
      condition: "!has(object.spec.queue) || object.spec.queue == ''"
  
  # 2. Default MinMember - Set to 1 if not specified
  - target:
      group: scheduling.volcano.sh
      version: v1beta1
      kind: PodGroup
    patchType: strategic
    patches:
    - op: add
      path: /spec/minMember
      value: 1
      condition: "!has(object.spec.minMember)"
  
  # 3. Default PriorityClassName if specified via annotation
  - target:
      group: scheduling.volcano.sh
      version: v1beta1
      kind: PodGroup
    patchType: strategic
    patches:
    - op: add
      path: /spec/priorityClassName
      value: object.metadata.annotations['scheduling.volcano.sh/priority-class']
      condition: |
        !has(object.spec.priorityClassName) &&
        has(object.metadata.annotations) &&
        has(object.metadata.annotations['scheduling.volcano.sh/priority-class']) &&
        object.metadata.annotations['scheduling.volcano.sh/priority-class'] != ""

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingAdmissionPolicyBinding
metadata:
  name: podgroup-mutation-policy-binding
  labels:
    volcano.sh/component: podgroup-webhook
    volcano.sh/migration: map
spec:
  policyName: podgroup-mutation-policy
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: name
        operator: NotIn
        values: ["kube-system", "kube-public", "kube-node-lease"]